# Navigation Links

[[main]]
  name = "A propos"
  url = "#about"
  weight = 10

[[main]]
  name = "Exp√©rience"
  url = "#experience"
  weight = 20

[[main]]
  name = "Projets"
  url = "#projects"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40